services:
  db:
    image: postgres:16
    container_name: postgres 
    restart: always
    environment:
      POSTGRES_DB: Reserva_Espacos 
      POSTGRES_USER: postgres 
      POSTGRES_PASSWORD: postgres 
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
